import type { Metadata } from "next";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import ThemeGallery from "../components/ThemeGallery";
import { CARD_TYPES } from "@/lib/studio";
export const metadata: Metadata = { title: "Documentation", description: "Build your GitHub profile with the gh-stats SVG API. Card endpoints, themes, embed examples, and self-hosting instructions." };
const base = process.env.NEXT_PUBLIC_SITE_URL || "https://gh-stats-plum-five.vercel.app";

export default function DocsPage() {
  return <><Header /><main id="main" className="shell docs-layout"><nav className="docs-nav" aria-label="Documentation sections"><span className="eyebrow">THE FIELD GUIDE</span>{["Quick start", "Endpoints", "Customization", "Themes", "Caching", "Self hosting", "Troubleshooting"].map(section => <a key={section} href={`#${section.toLowerCase().replaceAll(" ", "-")}`}>{section}</a>)}</nav><article className="docs-content"><span className="eyebrow">GH-STATS / DOCUMENTATION</span><h1>From API to README.<br />In a few lines.</h1><p>Every card is a lightweight SVG image. Use the <a className="text-link" href="/#studio">card studio →</a> to build visually, or compose an API URL yourself. The hosted service needs no signup or personal token.</p>
    <section id="quick-start"><h2>Your first card</h2><p>Replace <code>YOUR_USERNAME</code> and paste this into your GitHub profile’s README.md:</p><pre><code>{`![GitHub overview](${base}/api/stats?username=YOUR_USERNAME&theme=dark)`}</code></pre><h3>Match light and dark appearance</h3><p>GitHub’s image proxy does not reliably communicate a reader’s theme to an API. Use two explicit image sources:</p><pre><code>{`<picture>\n  <source media="(prefers-color-scheme: dark)"\n    srcset="${base}/api/stats?username=YOUR_USERNAME&amp;theme=dark" />\n  <img src="${base}/api/stats?username=YOUR_USERNAME&amp;theme=light"\n    alt="My GitHub overview" />\n</picture>`}</code></pre></section>
    <section id="endpoints"><h2>Nine cards. One simple API.</h2><table><thead><tr><th>Endpoint</th><th>What it shows</th></tr></thead><tbody>{CARD_TYPES.map(card => <tr key={card.id}><td><code>/api/{card.id}</code></td><td>{card.description}</td></tr>)}</tbody></table><p>Most cards accept <code>username</code>. Pinned repositories use <code>repo=owner/name</code>; gists use <code>id=GIST_ID</code>. WakaTime uses a WakaTime username with publicly shared statistics.</p><pre><code>{`${base}/api/pin?repo=SaumilP/gh-stats&theme=nord\n${base}/api/languages?username=octocat&layout=donut\n${base}/api/stats?username=octocat&format=json`}</code></pre><h3>What the numbers mean</h3><ul><li>Stars and forks cover up to 500 recently updated public repositories. Larger profiles are sampled; stats JSON includes <code>sampled</code> and <code>repositoryLimit</code>.</li><li>Contributions and streaks cover GitHub’s rolling past-year calendar. Use <code>commits_year=2025</code> for a specific year in the stats endpoint. All-time commit aggregation is not supported.</li><li>Language primary mode weights the main language of recent repositories by stars. Bytes mode inspects up to 10 selected public repositories and has a higher upstream cost.</li><li>Focus is a repository-language distribution, not a commit count or a measurement of time spent.</li><li>WakaTime shows the requested public account, never the deployment owner’s private data.</li></ul></section>
    <section id="customization"><h2>A few personal touches</h2><table><thead><tr><th>Parameter</th><th>Usage</th></tr></thead><tbody>{[["theme", "A named theme, e.g. dark, nord, radical"], ["custom_title", "A short card title"], ["title_color / text_color", "Hex colors, without the #"], ["bg_color / border_color", "Background and border overrides"], ["hide_border", "true to remove the card border"], ["border_radius", "Corner radius from 0 to 40"], ["layout", "Language/WakaTime: normal, compact, donut, donut-vertical, pie"], ["format", "svg (default) or json"], ["count / sort", "Repositories: 1–10; stars, forks, or updated"]].map(([name, desc]) => <tr key={name}><td><code>{name}</code></td><td>{desc}</td></tr>)}</tbody></table><p>Existing advanced renderer parameters remain supported where applicable. The studio exposes commonly useful controls and generates correctly encoded URLs.</p></section>
    <section id="themes"><h2>Find your palette.</h2><p>Select a theme to open it in the studio. These colors come directly from the API’s theme registry.</p><ThemeGallery /></section>
    <section id="caching"><h2>Daily updates. Fewer moving parts.</h2><p>GitHub data is cached independently of SVG styling for 24 hours. A new theme reuses the same snapshot. Refreshes happen on demand after expiry, so unused profiles consume no scheduled compute.</p><ul><li>Vercel’s CDN serves rendered cards. Origin responses carry a TTL based on the underlying snapshot’s age.</li><li>During temporary provider failures, snapshots can be reused up to a maximum total age of seven days. Stale responses use a shorter cache window.</li><li><code>X-Card-Status</code> reports <code>fresh</code>, <code>stale</code>, or <code>error</code>. <code>X-Data-Updated-At</code> records the oldest underlying snapshot used.</li><li>Public <code>refresh</code>, <code>cacheSeconds</code>, and <code>cache_seconds</code> parameters do not override the hosted daily-data policy.</li><li>GitHub’s own image proxy may retain an embed beyond the origin’s update time. A browser refresh cannot force that proxy to refresh.</li></ul></section>
    <section id="self-hosting"><h2>Your infrastructure. Your cards.</h2><p>Deploy this Next.js project on Vercel with Node.js 24. Set these server-side variables:</p><pre><code>{`GITHUB_TOKEN=your_public_data_token\nKV_REST_API_URL=your_upstash_rest_url\nKV_REST_API_TOKEN=your_upstash_rest_token\nNEXT_PUBLIC_SITE_URL=https://your-deployment.vercel.app`}</code></pre><p>Use a GitHub token with only the access needed for public data. Never use a <code>NEXT_PUBLIC_</code> prefix for secrets. Upstash’s <code>UPSTASH_REDIS_REST_URL</code> and <code>UPSTASH_REDIS_REST_TOKEN</code> names are also supported.</p><p>Without a shared cache, a bounded per-instance cache keeps local development functional, but cannot deduplicate work across Vercel instances. The homepage and examples are static and need no token.</p><h3>Optional static exports</h3><p>The pregeneration script can update selected cards daily in a public repository. It validates all responses before replacing existing files, and rejects SVG error cards. See the README for configuration.</p></section>
    <section id="troubleshooting"><h2>When something looks off</h2><ul><li><strong>Card shows an error:</strong> verify the username, repository, or gist is public. The studio offers a retry without bypassing the cache.</li><li><strong>Streak is unavailable:</strong> the service needs a valid server-side GitHub token for GraphQL, or a previously cached snapshot.</li><li><strong>Stats look old:</strong> check <code>X-Data-Updated-At</code>. Normal updates are daily; stale snapshots are used only within the retention window.</li><li><strong>Self-hosted service is degraded:</strong> inspect <a href="/api/health">/api/health</a> for token, cache, and quota status. Match <code>X-Request-Id</code> with Vercel function logs.</li></ul><p>Found a bug? <a className="text-link" href="https://github.com/SaumilP/gh-stats/issues">Open an issue →</a> Include the endpoint, approximate time, and request ID. Keep credentials out of reports.</p></section>
  </article></main><Footer /></>;
}
